
version: '3.8'
services: 
    db:
        image: postgres:15.1
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
        ports:
        - '5432:5432'
        expose:
         - 5432
        volumes: 
        - post_db:/var/lib/postgresql/data

    api-service:
        build: ./MyApp/
        volumes: 
             - ./MyApp/:/app/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
        image: api-service


volumes:
  post_db: