
version: '3.8'
services: 
    api-service:
        build: ./MyApp/
        volumes: 
            - ./MyApp/:/app/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
        container_name: api-service-1
        image: 12-api-service
